name: Download from Azure Git

# Controls when the workflow will run
on:
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      # https://learn.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-7.1&tabs=HTTP
      - run: |
          mkdir packages/api/src/localization/
          curl -u ${{ secrets.ADO_USERNAME }}:${{ secrets.ADO_TOKEN }} -o packages/api/src/localization/en-US.json https://dev.azure.com/bagie/Production/_apis/git/repositories/D365_CE/items?api-version=7.0\&download=true\&path=/Latest/CustomerCare_Apps/UI/Master/BotFramework-WebChat/packages/api/src/Localization/en-US.json

      - run: |
          if [ -z $(git status --porcelain) ];
          then
            git checkout -b loc-`date +"%s"`
            git commit -a -m "Localization sync"
            git push --set-upstream origin HEAD
            gh pr create --assignee compulim --base main --label area-localization --title "Localization sync"
          fi
